import sys
from pathlib import Path
import subprocess
import re

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from grow_compiler import VortexArtifactEmitter

def makefile(project, vortex_home):
    return f"""# Generated by measure_overhead.py.
VORTEX_HOME ?= {vortex_home}
VORTEX_BUILD_DIR ?= $(VORTEX_HOME)/build
PROJECT := {project}
STAGED_DIR := $(VORTEX_BUILD_DIR)/tests/kernel/$(PROJECT)

.PHONY: stage run-simx run-rtlsim clean-stage

stage:
\tmkdir -p "$(STAGED_DIR)"
\tcp main.cpp "$(STAGED_DIR)/main.cpp"
\tprintf '%s\\n' 'ROOT_DIR := $$(realpath ../../..)' 'include $$(ROOT_DIR)/config.mk' '' 'PROJECT := $(PROJECT)' 'SRC_DIR := $$(VORTEX_BUILD_DIR)/tests/kernel/$$(PROJECT)' 'SRCS := $$(SRC_DIR)/main.cpp' '' 'include $$(VORTEX_HOME)/tests/kernel/common.mk' > "$(STAGED_DIR)/Makefile"

run-simx: stage
	$(MAKE) -C "$(STAGED_DIR)" run-simx

run-rtlsim: stage
	$(MAKE) -C "$(STAGED_DIR)" run-rtlsim

clean-stage:
\trm -rf "$(STAGED_DIR)"
"""

def generate_and_run(name: str, body: str, sim_target: str = "simx") -> int:
    out_dir = ROOT / "artifacts" / "overhead_tests" / name
    out_dir.mkdir(parents=True, exist_ok=True)
    
    cpp_content = f"""#include <stdint.h>
#include <vx_print.h>
#include <vx_intrinsics.h>

int main() {{
{body}
}}
"""
    (out_dir / "main.cpp").write_text(cpp_content, encoding="utf-8")
    (out_dir / "Makefile").write_text(makefile(name, "~/vortex"), encoding="utf-8")
    
    # Sync to WSL
    subprocess.run(
        ["wsl.exe", "-e", "bash", "-c", "bash scripts/wsl_sync_from_windows.sh"],
        check=True,
        capture_output=True,
        cwd=ROOT
    )
    
    # Run simulator
    cmd = f"cd ~/hackathon-project && source .wsl_env && timeout 60 make -C artifacts/overhead_tests/{name} run-{sim_target}"
    result = subprocess.run(
        ["wsl.exe", "-e", "bash", "-c", cmd],
        capture_output=True,
        text=True,
        cwd=ROOT
    )
    
    stdout = result.stdout
    if "Passed!" in stdout or "Failed!" in stdout or "SIMX_CYCLES" in stdout:
        match = re.search(r"SIMX_CYCLES=(\d+)", stdout)
        if match:
            return int(match.group(1))
    print(f"Failed to run {name}: {stdout}")
    return -1

def main():
    sim_target = sys.argv[1] if len(sys.argv) > 1 else "simx"
    print(f"Running Baseline (N=0) on {sim_target}...")
    baseline_body = """  uint64_t start = vx_rdcycle();
  // empty
  uint64_t end = vx_rdcycle();
  vx_printf("SIMX_CYCLES=%d\\n", (int)(end - start));
  return 0;
"""
    baseline_cycles = generate_and_run("baseline", baseline_body, sim_target)
    print(f"Baseline Overhead: {baseline_cycles}")
    
    for op_name, op_asm in [("add", "add %[out], %[a], %[b]"), ("mul", "mul %[out], %[a], %[b]"), ("load", "lw %[out], 0(%[base])")]:
        print(f"\\nTesting {op_name}...")
        results = {}
        for n in [1, 8, 64]:
            if op_name == "load":
                asm_lines = '"\\n\\t" '.join(f'"{op_asm}"' for _ in range(n))
                body = f"""  volatile int32_t memory[4] = {{101, 202, 303, 404}};
  int32_t out = 0;
  uint64_t start = vx_rdcycle();
  __asm__ volatile (
      {asm_lines}
      : [out] "+r" (out)
      : [base] "r" (memory)
      : "memory"
  );
  uint64_t end = vx_rdcycle();
  vx_printf("SIMX_CYCLES=%d\\n", (int)(end - start));
  // force output to be live
  if (out == 1234) vx_printf("junk\\n"); 
  return 0;
"""
            else:
                asm_lines = '"\\n\\t" '.join(f'"{op_asm}"' for _ in range(n))
                body = f"""  int32_t a = 12;
  int32_t b = 7;
  int32_t out = 0;
  uint64_t start = vx_rdcycle();
  __asm__ volatile (
      {asm_lines}
      : [out] "+r" (out)
      : [a] "r" (a), [b] "r" (b)
  );
  uint64_t end = vx_rdcycle();
  vx_printf("SIMX_CYCLES=%d\\n", (int)(end - start));
  if (out == 1234) vx_printf("junk\\n"); 
  return 0;
"""
            cycles = generate_and_run(f"{op_name}_N{n}", body, sim_target)
            results[n] = cycles
            print(f"  N={n} -> {cycles} cycles")
            
        slope = (results[64] - results[8]) / (64 - 8)
        print(f"  Estimated marginal per-op cost: {slope:.2f}")

if __name__ == "__main__":
    main()
